CREATE TABLE admission_bonus (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id UUID NOT NULL REFERENCES users(id),
  student_id UUID NOT NULL REFERENCES students(id),
  bonus_type TEXT NOT NULL CHECK (bonus_type IN ('admission','reference_distribution')),
  bonus_amount DECIMAL(10,2) NOT NULL,
  trigger_event TEXT DEFAULT 'student_reached_university',
  eligible_date DATE,
  status TEXT DEFAULT 'pending_approval' CHECK (status IN ('pending_approval','approved','disbursed','hold','cancelled')),
  approved_by UUID REFERENCES users(id),
  approved_at TIMESTAMPTZ,
  disbursed_date DATE,
  payment_proof_url TEXT,
  notes TEXT,
  referrer_student_id UUID REFERENCES students(id),
  referrer_name TEXT,
  referrer_phone TEXT,
  referrer_amount DECIMAL(10,2),
  referrer_paid BOOLEAN DEFAULT false,
  referrer_paid_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(staff_id, student_id, bonus_type)
);
