CREATE TABLE leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  parent_phone TEXT,
  email TEXT,
  city TEXT,
  state TEXT,
  neet_score INT,
  neet_year INT,
  interest TEXT CHECK (interest IN ('mbbs_abroad_georgia','mbbs_abroad_kyrgyzstan','mbbs_abroad_both','neet_coaching','both','other')),
  preferred_country TEXT CHECK (preferred_country IN ('Georgia','Kyrgyzstan','Any','Other')),
  lead_source TEXT CHECK (lead_source IN ('walk-in','phone','social','b2b','referral','whatsapp','excel_upload','other')),
  lead_status TEXT DEFAULT 'new' CHECK (lead_status IN ('new','contacted','qualified','converted','lost','not_interested')),
  follow_up_date DATE,
  notes TEXT,
  assigned_staff_id UUID REFERENCES users(id),
  office_id UUID REFERENCES offices(id),
  b2b_partner_id UUID,
  uploaded_via TEXT DEFAULT 'manual' CHECK (uploaded_via IN ('manual','excel')),
  converted_to_student_id UUID REFERENCES students(id),
  converted_at TIMESTAMPTZ,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
