CREATE TABLE students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_code TEXT UNIQUE,
  full_name TEXT NOT NULL,
  father_name TEXT,
  mother_name TEXT,
  dob DATE,
  gender TEXT CHECK (gender IN ('male','female','other')),
  photo_url TEXT,
  email TEXT,
  phone TEXT NOT NULL,
  parent_phone TEXT,
  whatsapp TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  reference_source TEXT CHECK (reference_source IN ('walk-in','referral','b2b','social','coaching','agent','other')),
  reference_details TEXT,
  referrer_student_id UUID REFERENCES students(id),
  reference_partner_id UUID,
  assigned_staff_id UUID REFERENCES users(id),
  office_id UUID REFERENCES offices(id),
  funnel_stage TEXT DEFAULT 'lead_generated',
  current_stage_updated_at TIMESTAMPTZ DEFAULT NOW(),
  neet_score INT,
  neet_year INT,
  twelfth_percentage DECIMAL(5,2),
  board TEXT,
  school_name TEXT,
  selected_university TEXT CHECK (selected_university IN (
    'European University (EEU)',
    'East West University',
    'Alte University',
    'SEU Georgia',
    'International European University (IEU)',
    'Avicenna International Medical University',
    'Coming Soon - Kyrgyzstan',
    'Other'
  )),
  selected_country TEXT CHECK (selected_country IN ('Georgia','Kyrgyzstan','Other')),
  intake_year INT,
  intake_month TEXT,
  notes TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
